services:
  db:
    image: postgres:16-alpine
    container_name: tilawati_db
    environment:
      POSTGRES_DB: tilawati_db
      POSTGRES_USER: tilawati
      POSTGRES_PASSWORD: tilawati123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tilawati -d tilawati_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
